ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild

onlyBuiltDependencies:
  - better-sqlite3

packages:
  - "packages/*"
  - "plugins/*"
  - "."
  - "!**/test/**"

catalog:
  vite: ^8.0.0-beta.0
  solid-js: ^1.9.10
  tsdown: ^0.17.1
  unplugin-solid: ^1.0.0
